### ISSUE TITLE
List projects first in collections

### ISSUE THREAD

**Issue by poopsplat** [firebelly/scb#1]
Toyed around with what you've got going on in `collections.php` and `post-collections.php` and couldn't quickly see how the 'bios' and 'projects' order is being specified, but based on the design, should be 'projects' first, then 'bios':

<img width="574" alt="screen shot 2016-01-25 at 4 27 56 pm" src="https://cloud.githubusercontent.com/assets/2831517/12566783/11d12558-c381-11e5-931d-40320776d16e.png">

**Comment by poopsplat** [comment]
@natebeaty  also just trying this out — if this is stupid and you'd prefer an email, slack message, or messages message, let me know.

**Comment by natebeaty** [comment]
`ORDER BY cp.post_type, cp.position ASC` here: https://github.com/firebelly/scb/blob/master/web/app/themes/scb/lib/post-collections.php#L118

Can just change that to DESC to do `project, bio`
